services:
  postgresql:
    image: postgres:17.2
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
